### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by itsVale** [itsVale/Shitcord#1]
Keeping an eye on the compatibility to the Python 3 versions! For now, the library should be compatible to any Python 3 version but this could change with further development.

**Comment by itsVale** [comment]
Because of the current gevent version that is used, the library only offers support for Python 3.4+.

**Comment by Gamer1Chris** [comment]
Macht schneller!!!

**Comment by itsVale** [comment]
Yes, and because we most likely don't need any more dependencies which only support versions higher than 3.5, this issue is actually irrelevant too.
