### ISSUE TITLE
Gateway implementation broken

### ISSUE THREAD

**Issue by itsVale** [itsVale/Shitcord#17]
### Describe the Bug

_A clear and concise description of what the bug is._
After running a Client instance from the `experimental` branch, the bot just closes the connection to the Discord Gateway after receiving some strange errors. Some times, they are related to zlib-compression problems or yet unspecified errors.

### To Reproduce

_Steps to reproduce the behaviour:_

- Well, just run a client instance and see what happens.

### Expected behaviour

_A clear and concise description of what you expected to happen._
The bot will stay online, dispatches events, sends a heartbeats, and doesn't error when decoding/decompressing payloads.

### Screenshots

_If applicable, add screenshots to help explain your problem._

![Example Screenshot][screenshot-1]

### Specifications

**Desktop (please complete the following information):**

  - Hardware: Doesn't matter for this case. 
  - OS: Windows 10, Manjaro Linux, macOS High Sierra (confirmation of this bug)
  - Version: Shitcord 0.0.2b (experimental), Python 3.7.1

### Additional Context

_Add any other context about the problem here._

[//]: # (Add links to any screenshots or other relevant information below)

[screenshot-1]: https://ws3.sinaimg.cn/large/006tKfTcly1fr6kihddwhj30b008j74g.jpg

**Comment by G3bE** [comment]
I could reproduce this error on macOS Mojave. Fixed [here](https://github.com/itsVale/Shitcord/pull/15)

**Comment by itsVale** [comment]
These issues were just solved.

**Comment by itsVale** [comment]
Well, after some testing I can say that the issue isn't resolved. There are still problems when it comes to zlib-decompression that makes the WebSocketClient fail with an OSError.

**Comment by itsVale** [comment]
So far, so good. The problem should almost be solved now. But there are still problems when it comes to ETF encoding of payloads.

**Comment by itsVale** [comment]
Since async as the main branch has resolved all issues corresponding to zlib compression or etf encoding, this issue is no longer relevant.
